module ShortcodePhotoInline
  def self.parse(html)
    	html
      
    	# html = html.gsub(/\[photo-left (.+?)\]/) do |capture|
    	# 	["<div class='photo-left-shim'>",
     #         "<div class='photo-left-inner'>",
     #         "<img src='" + Photo.all.shuffle.first.url_for(size: '300x300') + "'>",
     #        "</div>",
     #        "</div>\n\n"].join("\n")
    	# end
    # 	html = html.gsub(/\[photo-inline (.+?)\]/) do |capture|
    # 		photo = Photo.find($1)
    #     src = photo.url_for(size: '1000x700') # todo: dimensions?!
  		# 	%Q{
    #       <!-- generated by shortcode_photo_inline -->
  		# 		<div class="photo-inline" data-photo-id="#{$1}">
    # 				<img src="#{src}">
    # 				<div class="meta">
    # 					<span class="caption">#{photo.caption}</span>
    # 					<span class="byline">#{photo.byline}</span>
    # 				</div>
  		# 		</div>
  		# 	}  		
    # 	end
  end
end